name: Run unit tests
 
on:
  push:
    branches: [development,main]
  pull_request:
    branches: [development,main]
 
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Install Packages
        run: |
          pip install flask
 
      - name: Display Branch Name
        run: |
           echo ${GITHUB_HEAD_REF}
 
      - name: Unit Test
        run: |
          ls -al
          chmod +x ${{ github.workspace }}/test.py
          python ${{ github.workspace }}/test.py
          coverage report -m --fail-under=80

